import json
import os
import random

raw_data = [
    ("A 28-year-old male at 5000 meters altitude develops severe respiratory alkalosis. Over the next 48 hours, his kidneys compensate. Which of the following transport mechanisms in the nephron is most directly inhibited to facilitate this compensation?", "Apical Na+/H+ exchanger (NHE3) in the proximal tubule", ["Basolateral Na+/K+ ATPase in the proximal tubule", "Basolateral Cl-/HCO3- exchanger in type A intercalated cells", "Apical pendrin (Cl-/HCO3- exchanger) in type B intercalated cells", "Apical epithelial sodium channel (ENaC) in the principal cells"], "At high altitude, respiratory alkalosis is compensated by renal bicarbonate excretion, achieved by decreasing H+ secretion in the proximal tubule via downregulation of apical NHE3.", "Renal Physiology"),
    ("A 15-year-old male presents with severe hypertension, hypokalemia, and metabolic alkalosis. Laboratory evaluation reveals suppressed renin and aldosterone levels. A genetic mutation is suspected. What is the most likely molecular defect?", "Gain-of-function mutation in the PPPXY motif of the epithelial sodium channel (ENaC)", ["Loss-of-function mutation in 11beta-hydroxysteroid dehydrogenase type 2", "Activating mutation in the mineralocorticoid receptor", "Loss-of-function mutation in the NKCC2 cotransporter", "Gain-of-function mutation in the ROMK channel"], "Liddle syndrome presents with pseudoaldosteronism due to a gain-of-function mutation in ENaC preventing its ubiquitination and degradation.", "Renal Physiology"),
    ("Which of the following mediators is most directly responsible for activating central chemoreceptors in the retrotrapezoid nucleus during hypercapnia?", "Hydrogen ions produced locally by carbonic anhydrase", ["Peripheral CO2 directly crossing the BBB and binding the receptor", "HCO3- actively transported across the choroid plexus", "Lactic acid produced by surrounding ischemic astrocytes", "Oxygen tension acting on heme-containing oxygen sensors"], "Central chemoreceptors respond to changes in CSF pH. CO2 crosses the BBB and is converted to H+ and HCO3- by carbonic anhydrase; the H+ then activates the receptors.", "Respiratory Physiology"),
    ("In ventricular cardiomyocytes, the inward current during phase 2 (plateau) of the action potential is electrically balanced primarily by which of the following?", "Outward IKr and IKs delayed rectifier potassium currents", ["Inward Na+/Ca2+ exchanger current", "Outward transient outward potassium current (Ito)", "Inward hyperpolarization-activated (If) current", "Outward ATP-sensitive potassium current"], "Phase 2 plateau is maintained by a balance between inward L-type calcium currents and outward delayed rectifier potassium currents (IKr and IKs).", "Cardiovascular Physiology"),
    ("Reperfusion of an ischemic cardiac vascular bed causes marked vasodilation, a phenomenon known as reactive hyperemia. This is primarily mediated by which of the following?", "Adenosine acting on A2A receptors opening K-ATP channels", ["Nitric oxide release from sheer-stressed endothelial cells", "Decreased sympathetic nerve activity to the vascular bed", "Myogenic relaxation of the smooth muscle following low pressure", "Endothelin-1 downregulation during ischemia"], "Reactive hyperemia in the heart is primarily mediated by adenosine, a byproduct of ATP breakdown during ischemia, which causes potent vasodilation.", "Cardiovascular Physiology"),
    ("During chronic metabolic acidosis, the kidney significantly upregulates ammoniagenesis to buffer secreted hydrogen ions. What is the primary source of this renal ammonia?", "Glutamine metabolism via glutaminase in the proximal tubule", ["Urea breakdown in the inner medullary collecting duct", "Conversion of alpha-ketoglutarate to glutamate in the distal tubule", "Ammonium secretion by type A intercalated cells", "Filtration of plasma ammonia across the glomerulus"], "During acidosis, proximal tubule cells extract glutamine and metabolize it via glutaminase to produce NH4+ and bicarbonate.", "Renal Physiology"),
    ("During states of low renal perfusion, angiotensin II plays a critical role in maintaining the glomerular filtration rate (GFR). It achieves this primarily via which mechanism?", "Preferential constriction of efferent arterioles via AT1 receptors", ["Dilation of afferent arterioles via local prostaglandins", "Constriction of both afferent and efferent arterioles equally", "Activation of renin release from juxtaglomerular cells", "Relaxation of mesangial cells to increase filtration surface area"], "Angiotensin II preferentially constricts the efferent arteriole, increasing glomerular hydrostatic pressure to maintain GFR when renal blood flow drops.", "Renal Physiology"),
    ("Intestinal absorption of glucose via the Sodium-Glucose Linked Transporter 1 (SGLT1) depends most directly on which of the following?", "The electrochemical sodium gradient maintained by basolateral Na/K ATPase", ["The presence of insulin to insert SGLT1 into the apical membrane", "Facilitated diffusion down the glucose concentration gradient", "Primary active transport utilizing ATP hydrolysis directly", "Antiport with intracellular potassium ions"], "SGLT1 uses secondary active transport. The energy is derived from the sodium gradient, which is maintained by the basolateral Na+/K+ ATPase.", "Gastrointestinal Physiology"),
    ("Gastrin stimulates parietal cell acid secretion primarily via which of the following intracellular signaling pathways?", "CCK-B receptors increasing intracellular calcium", ["H2 receptors increasing intracellular cAMP", "M3 receptors decreasing intracellular cAMP", "Direct activation of the H+/K+ ATPase via phosphorylation", "CCK-A receptors increasing intracellular cGMP"], "Gastrin binds to CCK-B receptors on parietal cells, activating the Gq pathway, which increases IP3 and intracellular calcium to stimulate H+ secretion.", "Gastrointestinal Physiology"),
    ("The spontaneous diastolic depolarization (Phase 4) in the sinoatrial node is driven primarily by which of the following ionic currents?", "Inward sodium (If) and transient calcium (T-type) currents", ["Outward potassium current and inward L-type calcium current", "Inward sodium current via fast voltage-gated channels", "Rapid activation of the delayed rectifier potassium channel", "Decreased activity of the Na+/Ca2+ exchanger"], "The pacemaker potential is initiated by the funny current (If, an inward Na+ current) and the transient (T-type) calcium current.", "Cardiovascular Physiology"),
    ("A neonate presents with polyhydramnios, hypokalemia, and metabolic alkalosis. Genetic testing reveals Type 2 Bartter syndrome. Which of the following transport proteins is defective?", "Apical ROMK potassium channel", ["Loss of function in the NKCC2 cotransporter", "Loss of function in the CLCNKB chloride channel", "Gain of function in the epithelial sodium channel (ENaC)", "Loss of function in the thiazide-sensitive NCC cotransporter"], "Type 2 Bartter syndrome is caused by loss-of-function mutations in KCNJ1, which encodes the ROMK potassium channel necessary for NKCC2 function.", "Renal Physiology"),
    ("The compliance of the respiratory system is lowest at which of the following lung volumes?", "Total lung capacity", ["Functional residual capacity", "Residual volume", "Tidal volume", "Closing capacity"], "At Total Lung Capacity (TLC), the lungs are highly stretched and the elastic tissues are near their limits, making them very stiff (lowest compliance).", "Respiratory Physiology"),
    ("Carbon monoxide poisoning reduces oxygen delivery to tissues primarily because it does which of the following?", "Stabilizes the R-state of hemoglobin, shifting the dissociation curve to the left", ["Decreases the partial pressure of oxygen (PaO2) significantly", "Shifts the dissociation curve to the right by binding 2,3-BPG", "Increases oxygen delivery to the tissues during exertion", "Forms methemoglobin preventing oxygen binding"], "CO binding to one heme group increases the oxygen affinity of the remaining heme groups (stabilizing the R-state), shifting the curve to the left and preventing oxygen unloading.", "Respiratory Physiology"),
    ("The Bezold-Jarisch reflex, characterized by apnea, bradycardia, and hypotension following noxious ventricular stimuli, is mediated by which of the following?", "Afferent vagal unmyelinated C-fibers", ["Sympathetic afferents from the epicardium", "Glossopharyngeal afferents from the carotid body", "Phrenic nerve efferents to the diaphragm", "Trigeminal afferents from the nasal mucosa"], "The Bezold-Jarisch reflex is a vagovagal reflex mediated by unmyelinated C-fiber afferents located in the ventricles.", "Cardiovascular Physiology"),
    ("Salivary fluid differs from plasma at high flow rates. Which of the following best describes the transport characteristics of salivary ductal cells?", "Absorb Na/Cl and secrete K/HCO3 while remaining impermeable to water", ["Acinar cells secrete a highly hypotonic initial fluid", "Ductal cells are freely permeable to water", "Aldosterone decreases potassium secretion in the ducts", "Parasympathetic tone makes the final fluid hypertonic"], "Salivary ducts reabsorb Na+ and Cl- and secrete K+ and HCO3-. Because they are impermeable to water, the final saliva becomes hypotonic.", "Gastrointestinal Physiology"),
    ("Secretin, a hormone released by S cells in the duodenum, stimulates pancreatic bicarbonate secretion by doing which of the following?", "Activating adenylate cyclase, increasing cAMP, and activating CFTR in duct cells", ["Activating phospholipase C in acinar cells", "Opening chloride channels in gastric G cells", "Directly stimulating enteropeptidase secretion in the duodenum", "Inhibiting CFTR channels to conserve bicarbonate"], "Secretin binds to Gs-coupled receptors on pancreatic duct cells, increasing cAMP, which activates CFTR channels to drive bicarbonate secretion.", "Gastrointestinal Physiology"),
    ("During skeletal muscle cross-bridge cycling, the binding of a new ATP molecule to the myosin head directly causes which of the following events?", "Detachment of the myosin head from the actin filament", ["Execution of the power stroke", "Binding of the myosin head to the actin filament", "Reuptake of calcium into the sarcoplasmic reticulum", "Conformational change of the tropomyosin complex"], "ATP binding to myosin decreases its affinity for actin, causing the cross-bridge to detach. ATP hydrolysis is later required to cock the myosin head.", "Neurophysiology"),
    ("Glycine functions as a major inhibitory neurotransmitter in the spinal cord by which of the following mechanisms?", "Opening ionotropic chloride channels causing postsynaptic hyperpolarization", ["Opening potassium channels via G-protein coupled receptors", "Closing voltage-gated calcium channels", "Depolarizing the postsynaptic membrane", "Acting directly via NMDA receptors"], "Glycine activates ionotropic receptors that are ligand-gated chloride channels. Chloride influx hyperpolarizes the postsynaptic membrane.", "Neurophysiology"),
    ("During prolonged fasting, glucagon maintains blood glucose primarily by modulating which of the following enzymes in the liver?", "Suppressing fructose-2,6-bisphosphate, which disinhibits FBPase-1", ["Activating glucokinase in hepatocytes", "Inhibiting glycogen phosphorylase", "Increasing malonyl-CoA to stimulate beta-oxidation", "Downregulating phosphoenolpyruvate carboxykinase (PEPCK)"], "Glucagon decreases fructose-2,6-bisphosphate levels via PKA phosphorylation. This relieves inhibition on fructose-1,6-bisphosphatase (FBPase-1), promoting gluconeogenesis.", "Endocrine Physiology"),
    ("Which of the following factors stabilizes the T-state of hemoglobin, decreasing its affinity for oxygen and promoting tissue unloading?", "Binding of 2,3-bisphosphoglycerate to the beta-chains", ["Binding of 2,3-bisphosphoglycerate to the alpha-chains", "Conversion of the heme iron from Fe2+ to Fe3+", "Increasing the oxygen affinity of the hemoglobin tetramer", "Competing with carbon monoxide for the heme binding site"], "2,3-BPG binds to the central cavity between the beta-chains of deoxyhemoglobin, stabilizing the taut (T) state and decreasing oxygen affinity.", "Respiratory Physiology"),
    ("A 40-year-old woman with an aldosterone-secreting adenoma does not develop massive peripheral edema. This phenomenon (aldosterone escape) is primarily due to which of the following?", "Aldosterone escape via pressure natriuresis and ANP release", ["Persistent progressive peripheral edema", "Hyperkalemic metabolic acidosis", "Decreased atrial natriuretic peptide levels", "High plasma renin activity due to hypovolemia"], "The initial volume expansion from aldosterone increases renal perfusion pressure (causing pressure natriuresis) and stretches the atria (releasing ANP), preventing edema.", "Renal Physiology"),
    ("Glomerular filtration rate (GFR) is most accurately estimated by measuring the renal clearance of a substance that exhibits which of the following properties?", "Freely filtered, but neither secreted nor reabsorbed", ["Para-aminohippuric acid (PAH)", "Creatinine, which provides an exact GFR without overestimation", "Urea, which is fully reabsorbed", "Cystatin C, which undergoes significant tubular secretion"], "An ideal GFR marker, such as inulin, must be freely filtered at the glomerulus and neither secreted nor reabsorbed by the tubules.", "Renal Physiology"),
    ("Pulmonary surfactant prevents alveolar collapse and increases lung compliance by which of the following mechanisms?", "Undergoing exocytosis from lamellar bodies in Type II pneumocytes in response to stretch", ["Being produced by Type I pneumocytes", "Increasing surface tension to prevent over-distension", "Its production being primarily stimulated by fetal insulin", "Decreasing overall lung compliance"], "Surfactant is stored in lamellar bodies in Type II pneumocytes and is released via exocytosis, which is mechanically stimulated by deep inspirations.", "Respiratory Physiology"),
    ("The Bainbridge reflex is an important cardiovascular reflex that occurs when which of the following happens?", "Increased atrial stretch accelerates the heart rate via vagal afferents", ["Ventricular stretch causes vagal bradycardia", "Aortic arch baroreceptors decrease heart rate", "Carotid sinus massage causes reflex tachycardia", "Systemic hypoxia triggers a sympathetic surge"], "Increased venous return stretches atrial stretch receptors, which send vagal afferent signals to the medulla, leading to an increase in heart rate to handle the volume.", "Cardiovascular Physiology"),
    ("Iron homeostasis is tightly regulated by the hepatic peptide hepcidin, which acts primarily by doing which of the following?", "Internalizing ferroportin to trap iron in enterocytes and macrophages", ["Stimulating the apical divalent metal transporter 1 (DMT1)", "Enhancing transferrin saturation in the systemic circulation", "Being secreted primarily by the kidney in response to hypoxia", "Upregulating hephaestin on the basolateral membrane"], "Hepcidin binds to the iron exporter ferroportin, causing its degradation. This traps iron in enterocytes (which are later sloughed off) and in reticuloendothelial macrophages.", "Gastrointestinal Physiology"),
    ("Somatostatin inhibits gastric acid secretion primarily through which of the following mechanisms?", "Paracrine inhibition via Gi-coupled receptors decreasing cAMP in parietal cells", ["Endocrine stimulation of parietal cells via systemic circulation", "Increasing intracellular calcium in antral G cells", "Being released by I cells in the duodenum", "Activating adenylate cyclase via Gs-coupled receptors"], "Somatostatin from D cells exerts a direct paracrine inhibitory effect on parietal cells by binding to Gi-coupled receptors, decreasing cAMP and inhibiting the proton pump.", "Gastrointestinal Physiology"),
    ("Saltatory conduction in myelinated axons is highly efficient due to which of the following biophysical features?", "High density of Nav1.6 channels concentrated at the nodes of Ranvier", ["Continuous opening of potassium channels along the internode", "Increased membrane capacitance provided by the myelin sheath", "Decreased transverse resistance of the axonal membrane", "Depolarization of the internodal segments"], "Myelin decreases membrane capacitance and increases transverse resistance. Action potentials jump between nodes of Ranvier, which contain a high density of voltage-gated sodium channels (Nav1.6).", "Neurophysiology"),
    ("In smooth muscle, an increase in intracellular calcium initiates contraction when calcium binds to which of the following?", "Calmodulin, which subsequently activates myosin light chain kinase", ["Troponin C, initiating cross-bridge cycling", "Actin filaments directly, exposing myosin binding sites", "Myosin light chain phosphatase, causing dephosphorylation", "NMDA receptors, allowing further calcium influx"], "Unlike skeletal muscle, smooth muscle lacks troponin. Calcium binds calmodulin, and the complex activates myosin light chain kinase (MLCK) to phosphorylate myosin.", "Neurophysiology"),
    ("The receptor for triiodothyronine (T3) exerts its physiologic effects primarily by which of the following mechanisms?", "Heterodimerizing with the retinoid X receptor (RXR) on specific DNA elements", ["A cytosolic receptor complex bound to heat shock proteins", "A G-protein coupled transmembrane receptor", "A receptor tyrosine kinase in the cell membrane", "An ionotropic receptor channel complex"], "The thyroid hormone receptor is a nuclear receptor that binds T3, heterodimerizes with RXR, and binds to thyroid response elements on DNA to alter gene transcription.", "Endocrine Physiology"),
    ("The maximum achievable medullary interstitial osmolality requires which of the following?", "ADH-stimulated urea transport via UT-A1 and UT-A3 in the inner medullary collecting duct", ["Aldosterone-mediated insertion of urea transporters in the PCT", "The countercurrent multiplier actively secreting urea", "The thick ascending limb being highly permeable to urea", "Vasa recta actively secreting NaCl into the interstitium"], "ADH inserts AQP2 and urea transporters (UT-A1/UT-A3) into the IMCD. Urea recycling into the interstitium is critical for generating maximum medullary hypertonicity.", "Renal Physiology"),
    ("A patient with primary adrenal insufficiency (Addison's disease) presents with hypotension and striking hyperpigmentation. The hyperpigmentation is due to?", "Lack of cortisol feedback leading to excessive POMC cleavage into ACTH and MSH", ["Excessive ACTH actively suppressing melanocyte function", "Hyperaldosteronism driving a concurrent hypokalemia", "A primary defect in the pituitary corticotrophs", "Medullary epinephrine deficiency causing the hypotension"], "Loss of cortisol removes negative feedback on the pituitary, increasing synthesis of pro-opiomelanocortin (POMC), which is cleaved into ACTH and Melanocyte-Stimulating Hormone (MSH).", "Endocrine Physiology"),
    ("Isosmotic reabsorption of water in the proximal convoluted tubule is primarily facilitated by which of the following mechanisms?", "Transcellular transport via Aquaporin-1 driven by active solute gradients", ["Regulated insertion of Aquaporin-2 by ADH", "Hyperosmotic reabsorption leaving a hypotonic tubular fluid", "Driven solely by high peritubular hydrostatic pressure", "Impermeability to water unless aldosterone is present"], "The proximal tubule reabsorbs ~65% of filtered water isosmotically, mainly via constitutively active Aquaporin-1 channels, driven by the active transport of sodium and other solutes.", "Renal Physiology"),
    ("Hypoxic pulmonary vasoconstriction optimizes ventilation/perfusion (V/Q) matching by which of the following cellular mechanisms?", "Hypoxia inhibiting voltage-gated potassium (Kv) channels, causing smooth muscle depolarization", ["Hypoxia stimulating local nitric oxide release", "Activation of K-ATP channels causing hyperpolarization", "Being mediated by vagal efferents to the pulmonary bed", "Resulting from systemic acidosis rather than local hypoxia"], "Alveolar hypoxia inhibits Kv channels in pulmonary smooth muscle, leading to depolarization, calcium influx, and consequent vasoconstriction to divert blood to well-ventilated areas.", "Respiratory Physiology"),
    ("The Cushing reflex, a critical response to severe increased intracranial pressure, is initiated by which of the following?", "Cerebral ischemia triggering massive sympathetic discharge to raise mean arterial pressure", ["Intracranial hypotension triggering reflex tachycardia", "Parasympathetic fibers primarily acting to increase MAP", "Medullary chemoreceptors sensing cerebral hyperoxia", "Hypothalamic osmoreceptors shrinking due to edema"], "Increased ICP compresses cerebral vessels, causing ischemia. This triggers an immense sympathetic discharge to raise MAP above ICP to restore cerebral blood flow, causing secondary bradycardia.", "Cardiovascular Physiology"),
    ("The enterohepatic circulation of bile acids relies on active reabsorption primarily occurring in which of the following locations?", "Terminal ileum via the apical sodium-dependent bile acid transporter", ["Passive diffusion in the duodenum", "Secondary active transport coupled with chloride", "Proton-coupled transport in the jejunum", "Endocytosis by hepatic Kupffer cells"], "Roughly 95% of secreted bile acids are actively reabsorbed in the terminal ileum by the apical sodium-dependent bile acid transporter (ASBT).", "Gastrointestinal Physiology"),
    ("The migrating motor complex (MMC), responsible for clearing undigested material from the stomach during fasting, is initiated by?", "Phase III bursts of electrical activity triggered by motilin", ["Continuous low-level contractions during feeding", "Being regulated entirely by parasympathetic vagal input", "Being initiated by the postprandial release of CCK", "Occurring exclusively in the large intestine"], "The MMC occurs during the interdigestive (fasting) state and is initiated every 90-120 minutes by the release of the hormone motilin, featuring intense Phase III contractions.", "Gastrointestinal Physiology"),
    ("The transduction of sound waves into electrical signals in cochlear hair cells occurs when which of the following takes place?", "Stereocilia bend toward the kinocilium, allowing potassium influx from the endolymph", ["Stereocilia bending away from the kinocilium opening Na+ channels", "Calcium influx primarily from the perilymph", "The endolymph having a high sodium and low potassium concentration", "Transduction occurring via G-protein coupled receptors"], "Bending of stereocilia toward the tallest kinocilium opens mechanically-gated transduction channels. Since endolymph is rich in potassium, K+ flows in and depolarizes the cell.", "Neurophysiology"),
    ("Slow, aching pain and temperature sensations from the skin are primarily transmitted by which type of nerve fibers?", "Unmyelinated C-fibers with conduction velocities of 0.5-2.0 m/s", ["Heavily myelinated fibers with fast conduction", "Fibers that convey fine touch and proprioception", "Fibers activated only by innocuous thermal stimuli", "Fibers found exclusively in somatic motor nerves"], "C-fibers are small-diameter, unmyelinated afferents that conduct slowly (0.5-2 m/s) and transmit slow/aching pain, temperature, and crude touch.", "Neurophysiology"),
    ("Insulin promotes glucose uptake into skeletal muscle and adipose tissue by which of the following specific pathways?", "Activating PI3K/Akt, leading to Rab-GTPase mediated exocytosis of GLUT4 vesicles", ["The cAMP pathway opening GLUT2 channels", "Direct phosphorylation of glucose to trap it intracellularly", "Inhibition of hexokinase activity", "Downregulation of Rab-GTPase activity"], "Insulin receptor activation phosphorylates IRS-1, activating PI3K and Akt, which phosphorylates AS160, allowing Rab-GTPases to drive GLUT4 vesicle translocation to the membrane.", "Endocrine Physiology"),
    ("Aldosterone increases sodium reabsorption in principal cells primarily by doing which of the following?", "Binding cytosolic receptors that translocate to the nucleus to induce SGK1 expression", ["A membrane-bound receptor activating phospholipase C", "Direct phosphorylation of ENaC by the receptor kinase", "Inhibiting basolateral Na/K ATPase transcription", "Acting via a cGMP secondary messenger cascade"], "Aldosterone is a steroid hormone that binds the cytosolic mineralocorticoid receptor. The complex alters transcription, heavily upregulating SGK1, which prevents ENaC degradation.", "Renal Physiology"),
    ("In the syndrome of inappropriate antidiuretic hormone (SIADH), the patient remains clinically euvolemic primarily because?", "Transient volume expansion triggers ANP release and pressure natriuresis", ["Hypovolemia stimulating the renin-angiotensin system", "Hyperuricemia due to increased PCT reabsorption", "Central pontine myelinolysis as the initial presentation", "Unsuppressed renin activity despite high volume"], "Excess ADH causes water retention and volume expansion. This stretches the atria to release ANP, and increases perfusion pressure (pressure natriuresis), matching sodium/water output to intake (euvolemia).", "Renal Physiology"),
    ("Glucose pathologically appears in the urine of a diabetic patient when which of the following conditions is met?", "The filtered load exceeds the transport maximum (Tm) of the proximal SGLT carriers", ["The proximal tubule cells lose ATP due to hypoxia", "GLUT2 transporters become rapidly internalized", "Insulin resistance develops in the tubular epithelial cells", "Glomerular permeability to glucose pathologically increases"], "Glucose is freely filtered and normally completely reabsorbed. Glycosuria occurs when the filtered load of glucose exceeds the finite number/capacity (Tm) of SGLT transporters (~375 mg/min).", "Renal Physiology"),
    ("Central sleep apnea, commonly presenting as Cheyne-Stokes respiration in patients with severe heart failure, is characterized by?", "Periodic loss of ventilatory drive from the medullary pre-Bötzinger complex", ["Upper airway collapse during intense inspiration", "Hypercapnia causing immediate awakening and gasp", "Paradoxical chest wall and abdominal movement", "Persistent diaphragmatic EMG activity during the apnea"], "Unlike obstructive sleep apnea, central sleep apnea exhibits an absolute lack of respiratory effort due to transient loss of medullary respiratory drive.", "Respiratory Physiology"),
    ("The Windkessel effect is a crucial element of cardiovascular hemodynamics. It refers to the ability of the aorta to do which of the following?", "Convert pulsatile cardiac output into continuous peripheral flow via elastic recoil", ["Venous pooling during prolonged standing", "Arteriolar constriction maintaining mean arterial pressure", "Capillary fluid shift during acute hemorrhage", "Ventricular suction during early rapid diastole"], "The highly elastic aorta distends during systole, storing potential energy. During diastole, elastic recoil pushes blood forward, maintaining continuous capillary flow despite a pulsatile heart.", "Cardiovascular Physiology"),
    ("The secretion of enzyme-rich pancreatic juice during the intestinal phase of digestion is primarily stimulated by which of the following?", "CCK acting via vagovagal reflexes and direct acinar CCK1 receptor activation", ["Secretin acting via cAMP to release zymogens", "Sympathetic stimulation being the primary driver", "Enteropeptidase directly cleaving amylase in the acini", "Somatostatin highly stimulating its secretion"], "Cholecystokinin (CCK), released by I cells in response to fat and protein, is the principal stimulant for pancreatic acinar enzyme secretion, largely acting through vagovagal reflexes.", "Gastrointestinal Physiology"),
    ("Vitamin B12 absorption requires an intact gastrointestinal tract. It is absorbed in the terminal ileum strictly after binding to which of the following?", "Intrinsic factor, via cubilin receptors", ["Being absorbed passively in the duodenum", "Requiring transcobalamin I for intestinal transport", "Intrinsic factor being produced by gastric chief cells", "Being internalized via pinocytosis in the jejunum"], "Dietary B12 binds haptocorrin, then intrinsic factor (secreted by parietal cells) in the duodenum. The IF-B12 complex is endocytosed by cubilin receptors in the terminal ileum.", "Gastrointestinal Physiology"),
    ("The knee jerk (patellar) reflex is a classic monosynaptic reflex. It is initiated when which of the following occurs?", "Muscle spindle stretch activates Group Ia afferents, which monosynaptically excite alpha motor neurons", ["Group Ib afferents inhibiting alpha motor neurons", "A polysynaptic reflex involving inhibitory interneurons", "Gamma motor neurons executing the muscle contraction", "Pain fibers triggering a flexor withdrawal reflex"], "Tapping the patellar tendon stretches the quadriceps muscle spindles. Group Ia afferent fibers fire and monosynaptically excite the alpha motor neurons of the identical muscle.", "Neurophysiology"),
    ("Purkinje cells of the cerebellar cortex are essential for the coordination of voluntary movement. They exert their effect by doing which of the following?", "Releasing GABA to exert inhibitory tone on the deep cerebellar nuclei", ["Granule cells serving as the main inhibitory output", "Mossy fibers directly inhibiting the Purkinje cells", "Climbing fibers using dopamine as a neurotransmitter", "Deep nuclei projecting exclusively to the spinal cord"], "Purkinje cells provide the sole output from the cerebellar cortex. They are entirely inhibitory and release GABA onto the deep cerebellar nuclei and vestibular nuclei.", "Neurophysiology"),
    ("Parathyroid hormone (PTH) rapidly increases serum calcium levels by which of the following mechanisms?", "Binding PTH1R on osteoblasts, increasing RANKL expression to stimulate osteoclasts", ["Binding osteoclasts directly to cause resorption", "Decreasing renal CYP27B1 (1-alpha-hydroxylase) activity", "Inhibiting calcium reabsorption in the thick ascending limb", "Promoting phosphate reabsorption in the proximal tubule"], "PTH receptors are located on osteoblasts. Activation increases RANKL and M-CSF, which subsequently bind to precursors to stimulate osteoclast differentiation and bone resorption.", "Endocrine Physiology"),
    ("The Haldane effect facilitates the transport of carbon dioxide from the tissues to the lungs because?", "Deoxygenation of hemoglobin increases its affinity for CO2 and its ability to buffer H+", ["Oxygenation increases carbon dioxide carriage", "Carbon dioxide preferentially binds to the heme iron", "Low pH shifts the oxygen dissociation curve to the right", "Hydrogen ions displace 2,3-BPG from the hemoglobin tetramer"], "As hemoglobin unloads oxygen (deoxygenation) in peripheral tissues, it becomes a better base, buffering more H+ and forming more carbaminohemoglobin, increasing the blood's total CO2 capacity.", "Respiratory Physiology")
]

out_file = r"E:\USAMA\MBBS Books\MCQ_Generator\batches\bank_batch_physiology.json"
os.makedirs(os.path.dirname(out_file), exist_ok=True)

letters = ['A', 'B', 'C', 'D', 'E'] * 10
random.shuffle(letters)

mcqs = []
for i, item in enumerate(raw_data):
    q, correct, distractors, exp, context = item
    ans_letter = letters[i]
    ans_idx = ord(ans_letter) - ord('A')
    
    random.shuffle(distractors)
    
    options = []
    d_idx = 0
    for j in range(5):
        if j == ans_idx:
            options.append(correct)
        else:
            options.append(distractors[d_idx])
            d_idx += 1
            
    mcqs.append({
        "question": q,
        "option_a": options[0],
        "option_b": options[1],
        "option_c": options[2],
        "option_d": options[3],
        "option_e": options[4],
        "correct_answer": ans_letter,
        "explanation": exp,
        "source_context": context
    })

with open(out_file, 'w', encoding='utf-8') as f:
    json.dump(mcqs, f, indent=4)

print(f"Generated {len(mcqs)} MCQs successfully.")
